# docker-compose.yml

version: '3'

volumes:
  els-data:
    driver: local
    name: "elasticsearch-data"

networks:
  robustup-network:
    driver: "bridge"
    name: "robustup-network"

name: "robustup"
services:
  robustup-backend:
    build:
      dockerfile: '.devcontainer/Dockerfile'
      context: '..'
    ports:
      - 8000:8000
    networks:
        - robustup-network
    volumes:
      - ..:/robustup-backend:cached
    mem_limit: 1g
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1:8000/admin"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 80s
    depends_on:
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - action.destructive_requires_name=false
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    mem_limit: 2g
    volumes:
      - els-data:/usr/share/elasticsearch/data
      - elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - robustup-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 180s
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1:9200/_cluster/health"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s